### ISSUE TITLE
Failed to load the title-bar-replacer package

### ISSUE THREAD

**Issue by xtoolkit** [sindrets/atom-title-bar-replacer#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [title-bar-replacer](https://github.com/sindrets/atom-title-bar-replacer) package 1.4.3

### Stack Trace

Failed to load the title-bar-replacer package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.20.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.20.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.20.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.20.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-title-bar-replacer/lib/title-bar-replacer-view.js:4:14)
    at /packages/atom-title-bar-replacer/lib/title-bar-replacer-view.js:646:12)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.20.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.20.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-title-bar-replacer/lib/title-bar-replacer.js:7:29)
    at /packages/atom-title-bar-replacer/lib/title-bar-replacer.js:531:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.20.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.0/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.20.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:887:35)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.20.0/resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.20.0/resources/app/src/package-manager.js:565:22)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/src/package-manager.js:479:25
```

### Commands

```
     -0:18.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
arshen-ac 0.9.6 
atom-beautify 0.30.4 
atom-json-color 0.6.0 
title-bar-replacer 1.4.3 
file-icons 2.1.9 
git-plus 7.9.3 
highlight-selected 0.13.1 
java-generator 2.2.3 
minimap 4.29.6 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
Remote-FTP 1.1.3 
tool-bar 1.1.0 
```

**Comment by xtoolkit** [comment]
i disable arshen-ac. but again not work

**Comment by sindrets** [comment]
Hello @xtoolkit. This error is most likely caused because you are missing the dependecies. Uninstall and reinstall the title bar replacer through the APM (either through Atom's package installation tab, or the apm command in CMD). If you cloned my github repository you have to run the ```npm install``` command in the repository folder to download dependencies.

**Comment by xtoolkit** [comment]
yes and work.
but chromebox icons not load and windows frame remover not work!

**Comment by sindrets** [comment]
Closing this issue as the original issue was resolved.

**Comment by sindrets** [comment]
@xtoolkit I'm gonna need more information to understand your new issue. Are there any errors in the console?

**Comment by Parthacus** [comment]
@sindrets I'm having the same issue, if you try and install it using the apm install command, it installs with no error in the console but if you actually try and then open atom the module will fail to load because it can't find the module jquery so what I think he means is that if you use the command line it installs but it won't load so there's no settings in the package

**Comment by sindrets** [comment]
@Parthacus hmm. The `apm` command should install all dependecies, but there has been issues in the past reported to Atom that it does not always do so. The current version of Atom seems to have some problems with write permissions on Windows. I have had problems updating my packages.

If the dependecies didn't get installed, close atom, open a command line, navigate to `%userprofile%/.atom/packages/title-bar-replacer`, and run `npm install`. Given that you have Node installed. This should download all package dependencies.

**Comment by codecrap** [comment]
> @Parthacus hmm. The `apm` command should install all dependecies, but there has been issues in the past reported to Atom that it does not always do so. The current version of Atom seems to have some problems with write permissions on Windows. I have had problems updating my packages.
> 
> If the dependecies didn't get installed, close atom, open a command line, navigate to `%userprofile%/.atom/packages/title-bar-replacer`, and run `npm install`. Given that you have Node installed. This should download all package dependencies.
> 

I am having the same issue with title-bar-replacer version 1.8.1 and Atom version 1.32.0 on Ubuntu Linux 18.10, but the above procedure does not help. I also checked to have the jQuery package installed. Here is the stack trace I'm getting:

`Cannot find module 'jQuery'
Hide Stack Trace
Error: Cannot find module 'jQuery'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:154364)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145671)
    at Object.<anonymous> (/home/redwombat/.atom/packages/title-bar-replacer/lib/title-bar-replacer-view.js:4:9)
    at Object.<anonymous> (/home/redwombat/.atom/packages/title-bar-replacer/lib/title-bar-replacer-view.js:600:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145671)
    at Object.<anonymous> (/home/redwombat/.atom/packages/title-bar-replacer/lib/title-bar-replacer.js:3:33)
    at Object.<anonymous> (/home/redwombat/.atom/packages/title-bar-replacer/lib/title-bar-replacer.js:610:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145671)
    at Object.<anonymous> (/home/redwombat/.atom/packages/title-bar-replacer/lib/index.js:3:26)
    at Object.<anonymous> (/home/redwombat/.atom/packages/title-bar-replacer/lib/index.js:27:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)`

**Comment by Bestshot99** [comment]
@sarahstrong I'm having the same issue. In which file did you replace all the require("jQuery")'s in?

**Comment by sarahstrong** [comment]
@Bestshot99 Looks like the version I got through APM does not yet include this commit, you can see the changes there: https://github.com/sindrets/atom-title-bar-replacer/commit/66c13640a81d39ce0c1623ddfc11108de6a2f087

**Comment by TheKoalaBoy** [comment]
> @sindrets : Replacing all instances of `require("jQuery")` with `require("jquery")` fixed the issue for me.

This solved my issue, ty!

**Comment by AR-Calder** [comment]
> @sindrets : Replacing all instances of `require("jQuery")` with `require("jquery")` fixed the issue for me.

This also solved the issue for me, on Manjaro Linux.

**Comment by HenriquePF** [comment]
Can someone tell me how to replace those instances? I'm kinda lost, sorry.

**Comment by AR-Calder** [comment]
@HenriquePF open the package it in a text editor, then use find and replace to find _require("jQuery")_ and replace all with _require("jquery")_
