### ISSUE TITLE
ENOENT: no such file or directory (atom-window.js)

### ISSUE THREAD

**Issue by shanewils92** [sindrets/atom-title-bar-replacer#13]
**Atom:** 1.21.0 x64
**Electron:** 1.6.9
**OS**: Microsoft Windows 10 Home x64
**Thrown From:** title-bar-replacer package 1.5.0

```
Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Synplex\AppData\Local\atom\app-1.21.0\resources\app\src\main-process\atom-window.js'
events.js:160 Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Synplex\AppData\Local\atom\app-1.21.0\resources\app\src\main-process\atom-window.js.bak'
fs.js:558 Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\Synplex\AppData\Local\atom\app-1.21.0\resources\app\src\main-process\atom-window.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at file:///C:/Users/Synplex/.atom/packages/title-bar-replacer/lib/window-frame-remover.js:159:27
```

**Comment by sindrets** [comment]
@shanewils92 This issue is caused by the new Atom 1.21. I will patch it soon, but for a temporary fix and more detail, see [this issue.](https://github.com/sindrets/atom-title-bar-replacer/issues/10#issuecomment-329159546)

**Comment by shanewils92** [comment]
Unfortunately, that temporary fix gives the same error plus some extra even with the asar package installed globally. If this package works fine on 1.20.0 then I'll downgrade until it's updated 😄

**Comment by sindrets** [comment]
@shanewils92 Hmm, strange. If you post the error here I can attempt to debug it.

Regardless, I'm glad that you appreciate my package :) I'll probably patch this tomorrow.

**Comment by shanewils92** [comment]
I love it, it's the one thing that made me switch to Visual Code. You're giving me a reason to return! Lol

```
--Navigating to the newest installed version of Atom...
----Newest detected installed version: app-1.21.0

--Creating extraction directory...

--Unpacking app.asar (might take some time: please remain patient)...

fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\Synplex\AppData\Local\atom\app-1.21.0\resources\app.asar'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.module.exports.readArchiveHeaderSync (C:\Users\Synplex\AppData\Roaming\npm\node_modules\asar\lib\disk.js:71:17)
    at Object.module.exports.readFilesystemSync (C:\Users\Synplex\AppData\Roaming\npm\node_modules\asar\lib\disk.js:97:25)
    at Object.module.exports.extractAll (C:\Users\Synplex\AppData\Roaming\npm\node_modules\asar\lib\asar.js:183:27)
    at Command.<anonymous> (C:\Users\Synplex\AppData\Roaming\npm\node_modules\asar\bin\asar.js:60:15)
    at Command.listener (C:\Users\Synplex\AppData\Roaming\npm\node_modules\asar\node_modules\commander\index.js:300:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (C:\Users\Synplex\AppData\Roaming\npm\node_modules\asar\node_modules\commander\index.js:635:12)
--Modifying atom-window.js...

The system cannot find the path specified.
Get-Content : Cannot find path 'C:\Users\Synplex\AppData\Local\atom\app-1.21.0\resources\atom-window.js' because it
does not exist.
At line:1 char:2
+ (Get-Content atom-window.js) | ForEach-Object { $_ -replace "options  ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Synple...\atom-window.js:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

--Renaming original app.asar

--Repacking modified app (might take some time: please remain patient)...
```

**Comment by shanewils92** [comment]
@sindrets 

Re-installed Atom and all is fine, I'm not sure why half the dir had been removed but hey-ho! 😃

**Comment by sindrets** [comment]
@shanewils92 v1.6 is now available with an implementation of the frame remover that is compatible with Atom v1.21.
