### ISSUE TITLE
Uncaught TypeError: Cannot read property 'paths' of undefined

### ISSUE THREAD

**Issue by Wargios** [sindrets/atom-title-bar-replacer#19]
[Enter steps to reproduce:]

1. I reopened a project through File → Reopen project
2. Atom refuses to reopen with this error.

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [title-bar-replacer](https://github.com/sindrets/atom-title-bar-replacer) package 1.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'paths' of undefined

```
At C:\Users\fcojg\AppData\Local\atom\app-1.22.1\resources\app\src\reopen-project-menu-manager.js:62

TypeError: Cannot read property 'paths' of undefined
    at ReopenProjectMenuManager.reopenProjectCommand (~/AppData/Local/atom/app-1.22.1/resources/app/src/reopen-project-menu-manager.js:62:54)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.22.1/resources/app/src/command-registry.js:266:23)
    at /packages/title-bar-replacer/lib/title-bar-replacer-view.ts:230:35)
    at HTMLDivElement.dispatch (/packages/title-bar-replacer/node_modules/jQuery/dist/jquery.js:4737:27)
    at HTMLDivElement.elemData.handle (/packages/title-bar-replacer/node_modules/jQuery/dist/jquery.js:4549:28)
```

### Commands

```
     -1:52.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -1:33.1.0 command-palette:toggle (atom-pane.pane)
     -1:29.2.0 github:toggle-git-tab (atom-pane.pane)
     -1:24.6.0 github:toggle-github-tab (atom-pane.pane)
  2x -1:14.4.0 tree-view:toggle (atom-pane.pane)
     -0:25 application:clear-project-history (atom-text-editor.editor)
  2x -0:19 application:reopen-project (atom-text-editor.editor)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-i18n 0.12.1 
file-icons 2.1.13 
php-cs-fixer 4.1.1 
Remote-FTP 1.3.1 
teletype 0.1.2 
title-bar-replacer 1.7.0 
```

**Comment by sindrets** [comment]
@Wargios hmm. I am not able to reproduce this. Does this happen every time you use that menu item? Does it happen when you try to reopen other projects?

**Comment by Wargios** [comment]
It can be an error with my packages. I reopen Atom only with replacer and it work again.
Sorry, my fault.

**Comment by sindrets** [comment]
@Wargios no worries. Glad you figured it out.
