### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getElementsByClassName' of undefined

### ISSUE THREAD

**Issue by occloxium** [sindrets/atom-title-bar-replacer#26]
[Enter steps to reproduce:]

1. Install title-bar-replacer like explained
2. Restart Atom after renaming the new app file
3. Error will display on any startup

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Windows 10 64bit
**Thrown From**: [title-bar-replacer](https://github.com/sindrets/atom-title-bar-replacer) package 1.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getElementsByClassName' of undefined

```
At C:\Users\Occloxium\.atom\packages\title-bar-replacer\lib\menu-updater.js:223

TypeError: Cannot read property 'getElementsByClassName' of undefined
    at MenuUpdater.buildAdditions (/packages/title-bar-replacer/lib/menu-updater.js:223:28)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:163:22)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
```

### Commands

```
```

### Non-Core Packages

```
antialiased 0.1.0 
atom-beautify 0.30.9 
atom-ide-ui 0.8.1 
atom-latex 0.8.4 
autoclose-html 0.23.0 
busy-signal 1.4.3 
color-picker 2.2.5 
ez-markdown 0.0.1 
highlight-selected 0.13.1 
ide-java 0.7.0 
ide-php 0.7.5 
ide-typescript 0.7.2 
intentions 1.1.5 
language-javascript-jsx 0.3.7 
language-latex 1.1.1 
language-markdown 0.25.1 
latex-autocomplete 1.1.1 
linter 2.2.0 
linter-markdown 5.2.0 
linter-php 1.5.1 
linter-sass-lint 1.8.3 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
neutron-dark-syntax 1.0.5 
neutron-dark-ui 2.1.4 
pdf-view 0.65.0 
sass-autocompile 0.13.5 
title-bar-replacer 1.8.1 
```

**Comment by sindrets** [comment]
@occloxium Did you figure this one out, or what happened? Sometimes these menu-updater errors (which happen rarely on my end) are simply fixed by running "Force rebuild title bar" from the command palette.

**Comment by occloxium** [comment]
Yes and as I seem to not be able to reproduce this issue consistently, I decided to close issue.

**Comment by MatthijsBlom** [comment]
I have the same problem. It used to work fine, but these last few days I keep getting this error. Perhaps linked to the upgrade to Atom 1.27.

<details><summary>Entire error message</summary>

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [title-bar-replacer](https://github.com/sindrets/atom-title-bar-replacer) package 1.8.1


### Stack Trace

Uncaught TypeError: Cannot read property 'getElementsByClassName' of undefined

```
At C:\Users\Matthijs\.atom\packages\title-bar-replacer\lib\menu-updater.js:215

TypeError: Cannot read property 'getElementsByClassName' of undefined
    at MenuUpdater.buildAdditions (/packages/title-bar-replacer/lib/menu-updater.js:215:17)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:163:22)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-clock 0.1.16 
atom-html-preview 0.2.5 
atom-latex 0.8.4 
autocomplete-haskell 1.0.1 
elm-format 3.0.0 
file-icons 2.1.21 
haskell-ghc-mod 2.2.3 
ide-haskell 2.3.1 
ide-haskell-repl 0.8.0 
language-batchfile 0.7.4 
language-elm 1.5.0 
language-haskell 1.17.7 
language-latex 1.1.1 
language-pfm 0.82.0 
language-restructuredtext 1.1.2 
language-svg 0.9.2 
linter 2.2.0 
linter-chktex 1.3.1 
linter-flake8 2.3.0 
linter-markdown 5.2.2 
linter-mypy 2.6.2 
linter-pycodestyle 2.1.3 
linter-pylint 2.1.1 
linter-shellcheck 1.4.7 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
MagicPython 1.0.12 
markdown-preview-plus 3.2.2 
pdf-view 0.70.0 
python-autopep8 0.1.3 
python-indent 1.1.5 
release-notes 0.53.0 
sort-lines 0.18.0 
statusbar-battery 0.11.3 
svg-preview 0.12.1 
tablr 1.8.3 
tidy-markdown 3.0.1 
title-bar-replacer 1.8.1 
toggle-quotes 1.1.0 
```
</details>
