### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by Geroyuni** [sindrets/atom-title-bar-replacer#27]
Steps:
1. Disable the package

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [title-bar-replacer](https://github.com/sindrets/atom-title-bar-replacer) package 1.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of null

```
At C:\Users\Geroyuni\.atom\packages\title-bar-replacer\lib\title-bar-replacer.js:252

TypeError: Cannot read property 'classList' of null
    at TitleBarReplacer.setMenuVisible (/packages/title-bar-replacer/lib/title-bar-replacer.js:252:48)
    at /packages/title-bar-replacer/lib/title-bar-replacer-view.js:140:44
    at dispatch (/packages/title-bar-replacer/node_modules/jQuery/dist/jquery.js:4737:27)
    at elemData.handle (/packages/title-bar-replacer/node_modules/jQuery/dist/jquery.js:4549:28)
```

### Commands

```
     -3:30.9.0 core:close (input.hidden-input)
     -0:35.5.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-material-ui 2.1.1 
auto-encoding 0.7.0 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.16 
highlight-selected 0.13.1 
intentions 1.1.5 
language-autohotkey2 1.0.1 
language-lua 0.9.11 
language-rainmeter 1.7.4 
linter 2.2.0 
linter-flake8 2.3.0 
linter-ui-default 1.6.10 
pigments 0.40.2 
python-indent 1.1.4 
script 3.17.3 
title-bar-replacer 1.8.1 
toggler 0.3.1 
```

**Comment by sindrets** [comment]
@Geroyuni hm, I'm unable to reproduce this on my end by disabling the package.

**Comment by Geroyuni** [comment]
Seems I assumed too many things incorrectly, excuse me. Seems related to #24 - Fixed that issue as well as this one by reinstalling the package.
