### ISSUE TITLE
Uncaught TypeError: Cannot read property 'childNodes' of null

### ISSUE THREAD

**Issue by carlo-fontanos** [sindrets/atom-title-bar-replacer#31]
**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [title-bar-replacer](https://github.com/sindrets/atom-title-bar-replacer) package 1.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'childNodes' of null

```
At C:\Users\Carl\.atom\packages\title-bar-replacer\lib\menu-updater.js:200

TypeError: Cannot read property 'childNodes' of null
    at MenuUpdater.updateLabel (/packages/title-bar-replacer/lib/menu-updater.js:200:17)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:152:22)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
```

### Commands

```
```

### Non-Core Packages

```
fonts 3.0.3 
hacking-the-kernel 1.6.2 
hacking-the-kernel-ui 1.6.2 
highlight-selected 0.13.1 
leet-syntax 1.0.0 
minimap 4.29.7 
move-panes 0.2.0 
pane-move-plus 0.3.1 
title-bar-replacer 1.8.1 
toggle-gutter 0.3.4 
```

**Comment by sindrets** [comment]
Fixed in v2.0.0.
