### ISSUE TITLE
Uncaught TypeError: Cannot set property 'ignoreHide' of undefined

### ISSUE THREAD

**Issue by jayin92** [sindrets/atom-title-bar-replacer#34]
[Enter steps to reproduce:]

An error when I don't select anything in the menu and press space

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [title-bar-replacer](https://github.com/sindrets/atom-title-bar-replacer) package 1.8.1

### Stack Trace

Uncaught TypeError: Cannot set property 'ignoreHide' of undefined

```
At C:\Users\jayinnn\.atom\packages\title-bar-replacer\lib\title-bar-replacer.js:591

TypeError: Cannot set property 'ignoreHide' of undefined
    at /packages/title-bar-replacer/lib/title-bar-replacer.js:591:42)
    at HTMLElement.dispatch (/packages/python-autopep8/node_modules/jquery/dist/jquery.js:4737:27)
    at HTMLElement.elemData.handle (/packages/python-autopep8/node_modules/jquery/dist/jquery.js:4549:28)
```

### Commands

```
     -3:31.5.0 core:backspace (input.hidden-input)
     -2:51.3.0 application:open-your-config (atom-pane.pane)
  2x -2:48.3.0 core:undo (input.hidden-input)
     -2:45.9.0 core:cut (input.hidden-input)
     -2:27.5.0 core:move-down (div.package-detail.panels-item)
     -2:26.7.0 core:move-up (div.package-detail.panels-item)
     -2:24.4.0 core:move-left (div.package-detail.panels-item)
  5x -2:24 core:move-right (div.package-detail.panels-item)
  4x -2:22.7.0 core:move-up (div.package-detail.panels-item)
  3x -2:21.5.0 core:move-down (div.package-detail.panels-item)
  4x -0:57 title-bar-replacer:toggle-title-bar (div.package-detail.panels-item)
  4x -0:47.5.0 title-bar-replacer:toggle-menu-bar (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-ide-ui 0.11.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autocomplete-python 1.10.5 
file-icons 2.1.18 
git-plus 7.10.2 
Hydrogen 2.4.1 
ide-python 0.9.2 
platformio-ide-terminal 2.8.1 
python-autopep8 0.1.3 
script 3.17.3 
sync-settings 0.8.6 
title-bar-replacer 1.8.1 
```

**Comment by sindrets** [comment]
Fixed in v2.0.0.
