### ISSUE TITLE
Uncaught TypeError: Cannot read property 'insertBefore' of undefined

### ISSUE THREAD

**Issue by AaronVigal** [sindrets/atom-title-bar-replacer#35]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [title-bar-replacer](https://github.com/sindrets/atom-title-bar-replacer) package 1.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'insertBefore' of undefined

```
At C:\Users\Aaron Vigal\.atom\packages\title-bar-replacer\lib\menu-updater.js:226

TypeError: Cannot read property 'insertBefore' of undefined
    at MenuUpdater.buildAdditions (/packages/title-bar-replacer/lib/menu-updater.js:226:17)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:163:22)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-ide-ui 0.11.2 
autosave-onchange 1.5.1 
file-icons 2.1.20 
highlight-selected 0.13.1 
ide-java 0.8.3 
minimap 4.29.8 
minimap-pigments 0.2.2 
pigments 0.40.2 
rest-client 1.3.1 
teletype 0.13.2 
title-bar-replacer 1.8.1 
wakatime 7.0.4 
```

**Comment by sindrets** [comment]
@AaronVigal duplicate issue. Closing in favor of #24
