### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by ElKroko** [sindrets/atom-title-bar-replacer#42]
Can someone tell me why this is happening? I just disabled the package and I'm getting a ton of error messages.

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Windows 10 Home
**Thrown From**: [title-bar-replacer](https://github.com/sindrets/atom-title-bar-replacer) package 1.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of null

```
At C:\Users\El Kroko\.atom\packages\title-bar-replacer\lib\title-bar-replacer.js:252

TypeError: Cannot read property 'classList' of null
    at TitleBarReplacer.setMenuVisible (/packages/title-bar-replacer/lib/title-bar-replacer.js:252:48)
    at /packages/title-bar-replacer/lib/title-bar-replacer-view.js:140:44
    at dispatch (/packages/title-bar-replacer/node_modules/jQuery/dist/jquery.js:4737:27)
    at elemData.handle (/packages/title-bar-replacer/node_modules/jQuery/dist/jquery.js:4549:28)
```

### Commands

```
     -7:29.6.0 core:confirm (input.hidden-input)
 15x -5:55 core:backspace (input.hidden-input)
     -5:31 core:confirm (input.hidden-input)
     -5:26.3.0 core:backspace (input.hidden-input)
     -4:12.6.0 core:cut (input.hidden-input)
     -4:01.9.0 core:confirm (input.hidden-input)
  3x -3:57.9.0 core:backspace (input.hidden-input)
     -3:47.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
neutron-dark-syntax 1.0.5 
neutron-dark-ui 2.1.4 
platformio-ide-terminal 2.8.4 
script 3.18.1 
teletype 0.13.3 
title-bar-replacer 1.8.1 
```

**Comment by sindrets** [comment]
Fixed in v2.0.0.
