### ISSUE TITLE
Uncaught Error: EEXIST: file already exists, mkdir '~/AppData\Local\atom\app-1.31.2\resources\app...

### ISSUE THREAD

**Issue by danhab99** [sindrets/atom-title-bar-replacer#44]
[Enter steps to reproduce:]

1. Check `Remove Window Frame`

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Home Insider Preview
**Thrown From**: [title-bar-replacer](https://github.com/sindrets/atom-title-bar-replacer) package 1.8.1

### Stack Trace

Uncaught Error: EEXIST: file already exists, mkdir 'C:\Users\danha\AppData\Local\atom\app-1.31.2\resources\app.asar.bak.unpacked\node_modules'

```
At fs.js:885

Error: EEXIST: file already exists, mkdir 'C:\Users\danha\AppData\Local\atom\app-1.31.2\resources\app.asar.bak.unpacked\node_modules'
    at fs.mkdirSync (fs.js:885:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:709:16)
    at /packages/title-bar-replacer/lib/window-frame-remover.js:162:24
    at Array.forEach (<anonymous>)
    at traverse (/packages/title-bar-replacer/lib/window-frame-remover.js:159:19)
    at WindowFrameRemover.copyFolderRecursiveSync (/packages/title-bar-replacer/lib/window-frame-remover.js:170:9)
    at /packages/title-bar-replacer/lib/window-frame-remover.js:286:31
```

### Non-Core Packages

```
atom-beautify 0.33.1 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
autoclose-html 0.23.0 
autocomplete-clang 0.11.5 
clang-format 1.30.0 
file-icons 2.1.24 
intentions 1.1.5 
language-babel 2.85.0 
language-gherkin-i18n 1.3.4 
language-powershell 4.0.1 
linter 2.0.0 
linter-clang 4.1.2 
linter-ui-default 1.7.1 
motivation undefined 
react 0.18.0 
title-bar-replacer 1.8.1 
tree-view-git-status 1.5.2 
vim-mode-plus 1.34.0 
Zen 0.18.0 
```

**Comment by sindrets** [comment]
Fixed in v2.0.0.
