### ISSUE TITLE
Failed to load the title-bar-replacer package Cannot find module 'jQuery'

### ISSUE THREAD

**Issue by LeptoSpira** [sindrets/atom-title-bar-replacer#51]
This issue has been closed before, but none of the answers has helped me.
I am on `Fedora Workstation 30`.

Stack Trace:
```
Error: Cannot find module 'jQuery'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:154765)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146072)
    at Object.<anonymous> (/home/LeptoSpira/.atom/packages/title-bar-replacer/lib/title-bar-replacer-view.js:4:9)
    at Object.<anonymous> (/home/LeptoSpira/.atom/packages/title-bar-replacer/lib/title-bar-replacer-view.js:600:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146072)
    at Object.<anonymous> (/home/LeptoSpira/.atom/packages/title-bar-replacer/lib/title-bar-replacer.js:3:33)
    at Object.<anonymous> (/home/LeptoSpira/.atom/packages/title-bar-replacer/lib/title-bar-replacer.js:610:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146072)
    at Object.<anonymous> (/home/LeptoSpira/.atom/packages/title-bar-replacer/lib/index.js:3:26)
    at Object.<anonymous> (/home/LeptoSpira/.atom/packages/title-bar-replacer/lib/index.js:27:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

**Comment by LeptoSpira** [comment]
Nevermind, forgot one of the updates

**Comment by codecrap** [comment]
Which update do you mean? I am having the exact same issue, everything is up-to-date and jQuery package is installed.
