### ISSUE TITLE
Uncaught TypeError: Cannot read property 'insertBefore' of undefined

### ISSUE THREAD

**Issue by sigmasoldi3r** [sindrets/atom-title-bar-replacer#57]
[Enter steps to reproduce:]

I cannot ensure at which point the error happened, but that's what I was doing so far:

1. Uninstall linter + linter dependencies
2. Install atom-ide package
2. Restart the atom editor

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [title-bar-replacer](https://github.com/sindrets/atom-title-bar-replacer) package 1.8.3

### Stack Trace

Uncaught TypeError: Cannot read property 'insertBefore' of undefined

```
At C:\Users\pablo\.atom\packages\title-bar-replacer\lib\menu-updater.js:226

TypeError: Cannot read property 'insertBefore' of undefined
    at MenuUpdater.buildAdditions (/packages/title-bar-replacer/lib/menu-updater.js:226:18)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:163:22)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
    at MenuUpdater.traverseTemplate (/packages/title-bar-replacer/lib/menu-updater.js:171:14)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-typescript 13.4.0 
clear-night-ui 1.4.2 
editor-background 1.2.42 
ide-cpp 0.1.0 
night-owl-syntax 1.0.1 
night-owl-theme-syntax 0.6.0 
night-owl-theme-ui 0.1.0 
night-owl-ui 1.1.0 
night-owl-vs-code-syntax 0.10.0 
night-sky-ui 0.3.0 
notebook-ui 0.2.0 
nucleus-dark-ui 0.12.3 
pen-paper-coffee-syntax 0.17.0 
pp-markdown 0.0.2 
pulsing-cursor 0.3.2 
seti-icons 1.5.4 
seti-syntax 1.2.0 
seti-ui 1.11.0 
simple-background 0.1.2 
title-bar-replacer 1.8.3 
tree-view-background 0.4.4 
unity-shader-files 0.3.1 
waterpaper-ui 0.1.0 
windows-context-menu 0.3.1 
wombat-dark-syntax 1.2.0 
```

**Comment by sigmasoldi3r** [comment]
I have seen now that this is already discussed at #24 

Closing as duplicate
